<?php

namespace AppBundle\Repository;

/**
 * AssessmentTypeSystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentTypeSystemRepository extends \Doctrine\ORM\EntityRepository
{
}
