<?php

namespace AppBundle\Repository;

/**
 * AssessmentResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentResultRepository extends \Doctrine\ORM\EntityRepository
{
}
