<?php

namespace AppBundle\Repository;

/**
 * AssessmentSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
