<?php

namespace AppBundle\Repository;

/**
 * CGPARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CGPARepository extends \Doctrine\ORM\EntityRepository
{
}
