<?php

namespace AppBundle\Repository;

/**
 * CourseGPARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseGPARepository extends \Doctrine\ORM\EntityRepository
{
}
