<?php

namespace AppBundle\Repository;

/**
 * curriculumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class curriculumRepository extends \Doctrine\ORM\EntityRepository
{
}
