<?php

namespace AppBundle\Repository;

/**
 * GPAResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GPAResultRepository extends \Doctrine\ORM\EntityRepository
{
}
