<?php

namespace AppBundle\Repository;

/**
 * GPARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GPARepository extends \Doctrine\ORM\EntityRepository
{
}
