<?php

namespace AppBundle\Repository;

/**
 * GPASystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GPASystemRepository extends \Doctrine\ORM\EntityRepository
{
}
