<?php

namespace AppBundle\Repository;

/**
 * GradeSystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeSystemRepository extends \Doctrine\ORM\EntityRepository
{
}
