<?php

namespace AppBundle\Repository;

/**
 * LogInTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogInTableRepository extends \Doctrine\ORM\EntityRepository
{
}
