<?php

namespace AppBundle\Repository;

/**
 * Minor_CoordinatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Minor_CoordinatorRepository extends \Doctrine\ORM\EntityRepository
{
}
