<?php

namespace AppBundle\Repository;

/**
 * ModuleGPARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleGPARepository extends \Doctrine\ORM\EntityRepository
{
}
