<?php

namespace AppBundle\Repository;

/**
 * PrerequisitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrerequisitesRepository extends \Doctrine\ORM\EntityRepository
{
}
