<?php

namespace AppBundle\Repository;

/**
 * SemesterGPARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemesterGPARepository extends \Doctrine\ORM\EntityRepository
{
}
