<?php

namespace AppBundle\Repository;

/**
 * SessionResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionResultRepository extends \Doctrine\ORM\EntityRepository
{
}
