AppBundle\Entity\AssessmentResult:
    type: entity
    table: assessment_result
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        resultValue:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: result_value
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    manyToOne:
      sessionId:
        targetEntity: Schoolsession
        inversedBy: assessment_result
        joinColumn:
          name: session_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
      studentId:
        targetEntity: Student
        inversedBy: assessment_result
        joinColumn:
          name: student_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
      assessmentTypeId:
        targetEntity: AssessmentType
        inversedBy: assessment_result
        joinColumn:
          name: assessment_type_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
