AppBundle\Entity\AssessmentType:
    type: entity
    table: assessment_type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        assessmentName:
            type: string
            nullable: false
            length: 75
            options:
                fixed: false
            column: assessment_name
        assessmentWorth:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: assessment_worth
        assessmentTypeSystemId:
            type: integer
            column: assessment_type_system_id
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
