AppBundle\Entity\Batch:
    type: entity
    table: batch
    uniqueConstraints:
        UNIQ_F80B52D4E771DA67:
            columns:
                - batch_code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        batchCode:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: batch_code
        batchName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: batch_name
        batchStartYear:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: batch_start_year
        batchEndYear:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: batch_end_year
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    oneToMany:
      sections:
        targetEntity: Section
        mappedBy: batch
    manyToOne:
      schoolId:
        targetEntity: School
        inversedBy: batch
        joinColumn:
          name: school_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
