AppBundle\Entity\CourseGPA:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CourseGPARepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        gpaValue:
            type: string
            length: '5'
            column: GPAValue
        creditHour:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: credit_hour
        totalSum:
            type: string
            length: '5'
            column: TotalSum
    lifecycleCallbacks: {  }
    manyToOne:
      studentId:
        targetEntity: Student
        inversedBy: coursegpa
        joinColumn:
          name: student_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
      courseId:
        targetEntity: Course
        inversedBy: coursegpa
        joinColumn:
          name: course_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
