AppBundle\Entity\Course:
    type: entity
    table: course
    uniqueConstraints:
        course_code_UNIQUE:
            columns:
                - course_code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        courseCode:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: course_code
        courseName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: course_name
        courseCreditHour:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: course_credit_hour
        curriculumId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: curriculum_id
        moduleId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: module_id
        semesterId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: semester_id
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
