AppBundle\Entity\Course:
    type: entity
    table: course
    uniqueConstraints:
        course_code_UNIQUE:
            columns:
                - course_code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        courseCode:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: course_code
        courseName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: course_name
        courseCreditHour:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: course_credit_hour
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    oneToMany:
      schoolsessions:
        targetEntity: Schoolsession
        mappedBy: module
    manyToOne:
      curriculumId:
        targetEntity: Curriculum
        inversedBy: course
        joinColumn:
          name: curriculum_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
      moduleId:
        targetEntity: Module
        inversedBy: course
        joinColumn:
          name: module_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
      semesterId:
        targetEntity: Semester
        inversedBy: course
        joinColumn:
          name: semester_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
