AppBundle\Entity\Curriculum:
    type: entity
    table: curriculum
    uniqueConstraints:
        UNIQ_7BE2A7C3329457C7:
            columns:
                - curriculum_code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        curriculumCode:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: curriculum_code
        curriculumName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: curriculum_name
        curriculumType:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: curriculum_type
        isApplied:
            type: boolean
            nullable: true
            column: is_applied


        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    oneToMany:
      modules:
        targetEntity: Module
        mappedBy: curriculum
      semesters:
        targetEntity: Semester
        mappedBy: curriculum
      courses:
        targetEntity: Course
        mappedBy: curriculum
    
      sections:
        targetEntity: Section
        mappedBy: curriculum
    manyToOne:
      schoolId:
        targetEntity: School
        inversedBy: curriculum
        joinColumn:
          name: school_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
      gradeSystemId:
        targetEntity: GradeSystem
        inversedBy: curriculum
        joinColumn:
          name: gradeSystemId
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
