AppBundle\Entity\Department:
    type: entity
    table: department
    uniqueConstraints:
        UNIQ_CD1DE18AD50F57CD:
            columns:
                - department_code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        departmentCode:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: department_code
        departmentName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: department_name

        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    oneToMany:
      teachers:
        targetEntity: Teacher
        mappedBy: department
    manyToOne:
      schoolId:
        targetEntity: School
        inversedBy: department
        joinColumn:
          name: school_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
