AppBundle\Entity\Department:
    type: entity
    table: department
    uniqueConstraints:
        UNIQ_CD1DE18AD50F57CD:
            columns:
                - department_code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        departmentCode:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: department_code
        departmentName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: department_name
        schoolId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: school_id
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    manyToOne:
        school:
            targetEntity: School
            inversedBy: departments
            joinColumn:
                name: school_id
                referencedColumnName: id
                onDelete: CASCADE
    oneToMany:
        teachers:
            targetEntity: Teacher
            mappedBy: department
