AppBundle\Entity\GPA:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GPARepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        startGpa:
            type: string
            length: '5'
            column: start_gpa
        endGpa:
            type: string
            length: '5'
            column: end_gpa
        gpaRemark:
            type: string
            length: '50'
            column: gpa_remark
        gpaPF:
            type: string
            length: '10'
            column: gpa_pf
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    manyToOne:
      gpaSystemId:
        targetEntity: GPASystem
        inversedBy: gpa
        joinColumn:
          name: gpa_system_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
