AppBundle\Entity\GPAResult:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GPAResultRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        gpaValue:
            type: string
            length: '5'
            nullable: true
            column: GpaValue
        gpaType:
            type: string
            length: '15'
            column: GpaType
    lifecycleCallbacks: {  }
    
