AppBundle\Entity\GPASystem:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GPASystemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        gpaSystemCode:
            type: string
            length: '100'
            unique: true
            column: gpa_system_code
        gpaSystemName:
            type: string
            length: 255
            column: gpa_system_name
        createdBy:
            type: integer
            column: created_by
    lifecycleCallbacks: {  }
    oneToMany:
      curriculums:
        targetEntity: Curriculum
        mappedBy: gpaSystem
      gpa:
        targetEntity: GPA
        mappedBy: gpaSystem
