AppBundle\Entity\Grade:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GradeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        startPoint:
            type: string
            length: '5'
            column: start_point
        endPoint:
            type: string
            length: '5'
            column: end_point
        grade:
            type: string
            length: '2'
        gradeValue:
            type: string
            length: '5'
        gradeRemark:
            type: string
            length: '10'
            column: grade_remark
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    manyToOne:
      gradeSystemId:
        targetEntity: GradeSystem
        inversedBy: grade
        joinColumn:
          name: grade_system_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
