AppBundle\Entity\MinorCoordinator:
    type: entity
    table: minor_coordinator
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        minorId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: minor_id
    lifecycleCallbacks: {  }
