AppBundle\Entity\Module:
    type: entity
    table: module
    uniqueConstraints:
        UNIQ_C242628CD297594:
            columns:
                - module_code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        moduleCode:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: module_code
        moduleName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: module_name
        moduleCreditHour:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: module_credit_hour
        moduleDuration:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            column: module_duration


        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    oneToMany:
      courses:
        targetEntity: Course
        mappedBy: module
    manyToOne:
      curriculumId:
        targetEntity: Curriculum
        inversedBy: module
        joinColumn:
          name: curriculum_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
