AppBundle\Entity\Prerequisite:
    type: entity
    table: prerequisite
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        courseModuleType:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: course_module_type
        prerequisiteType:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: prerequisite_type
    lifecycleCallbacks: {  }
    manyToOne:
      courseId:
        targetEntity: Course
        inversedBy: prerequisite
        joinColumn:
          name: course_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
      moduleId:
        targetEntity: Module
        inversedBy: prerequisite
        joinColumn:
          name: module_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
      prerequisiteCourseId:
        targetEntity: Course
        inversedBy: prerequisite
        joinColumn:
          name: prerequisite_course_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
      prerequisiteModuleId:
        targetEntity: Module
        inversedBy: prerequisite
        joinColumn:
          name: prerequisite_module_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
