AppBundle\Entity\Result:
    type: entity
    table: result
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sessionId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: session_id
        studentId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: student_id
        resultInNumber:
            type: string
            nullable: false
            length: 7
            options:
                fixed: false
            column: result_in_number
        resultInAlphabet:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
            column: result_in_alphabet
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
