AppBundle\Entity\Schoolsession:
    type: entity
    table: schoolsession
    uniqueConstraints:
        session_code_UNIQUE:
            columns:
                - session_code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sessionCode:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: session_code
        sessionName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: session_name

        courseModuleType:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: course_module_type

        sessionStartDate:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: session_start_date
        sessionEndDate:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: session_end_date
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    manyToOne:
      sectionId:
        targetEntity: Section
        inversedBy: schoolsession
        joinColumn:
          name: section_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
      teacherId:
        targetEntity: Teacher
        inversedBy: schoolsession
        joinColumn:
          name: teacher_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
      courseId:
        targetEntity: Course
        inversedBy: schoolsession
        joinColumn:
          name: course_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
      moduleId:
        targetEntity: Module
        inversedBy: schoolsession
        joinColumn:
          name: module_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
