AppBundle\Entity\Schoolsession:
    type: entity
    table: schoolsession
    uniqueConstraints:
        session_code_UNIQUE:
            columns:
                - session_code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sessionCode:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: session_code
        sessionName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: session_name
        courseModuleType:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: course_module_type
        sessionStartDate:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: session_start_date
        sessionEndDate:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: session_end_date
        sessionResultDeadline:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: session_result_deadline
        sessionRemark:
            type: string
            nullable: true
            length: '10'
            column: session_remark
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    oneToMany:
      sessionresult:
        targetEntity: SessionResult
        mappedBy: schoolsession
      sessionadd:
        targetEntity: SessionResultAdd
        mappedBy: schoolsession
    assessmentResults:
        targetEntity: AssessmentResult
        mappedBy: schoolsession
    manyToOne:
      sectionId:
        targetEntity: Section
        inversedBy: schoolsession
        joinColumn:
          name: section_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
      teacherId:
        targetEntity: Teacher
        inversedBy: schoolsession
        joinColumn:
          name: teacher_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
      courseId:
        targetEntity: Course
        inversedBy: schoolsession
        joinColumn:
          name: course_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
      moduleId:
        targetEntity: Module
        inversedBy: schoolsession
        joinColumn:
          name: module_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
      assessmentTypeSystemId:
        targetEntity: AssessmentTypeSystem
        inversedBy: schoolsession
        joinColumn:
          name: assessment_type_system_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
