AppBundle\Entity\SemesterGPA:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SemesterGPARepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        gpaValue:
            type: string
            length: '5'
            column: GPAValue
        creditHour:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: credit_hour
        totalSum:
            type: string
            length: '5'
            column: TotalSum
    lifecycleCallbacks: {  }
    manyToOne:
      studentId:
        targetEntity: Student
        inversedBy: semestergpa
        joinColumn:
          name: student_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
      semesterId:
        targetEntity: Semester
        inversedBy: semestergpa
        joinColumn:
          name: semester_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
