AppBundle\Entity\Semester:
    type: entity
    table: semester
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        semester:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        year:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false

        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    oneToMany:
      courses:
        targetEntity: Course
        mappedBy: semester
      semesterResults:
        targetEntity: SemesterGPA
        mappedBy: student
    manyToOne:
      curriculumId:
        targetEntity: Curriculum
        inversedBy: semester
        joinColumn:
          name: curriculum_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
