AppBundle\Entity\SessionResult:
    type: entity
    table: session_result
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        resultInNumber:
            type: string
            nullable: true
            length: 7
            options:
                fixed: false
            column: result_in_number
        resultInAlphabet:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: result_in_alphabet
        sessionResultRemark:
            type: string
            nullable: true
            length: '10'
            column: session_result_remark
        createdBy:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
    manyToOne:
      sessionId:
        targetEntity: Schoolsession
        inversedBy: session_result
        joinColumn:
          name: session_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
      studentId:
        targetEntity: Student
        inversedBy: session_result
        joinColumn:
          name: student_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
